VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsServerInfoHeader"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public CurrentDataOffset As Long
Public HeaderSeqID As Long
Public DataSize As Long
Public ServerCount As Long
Public ServersSoFar As Long


Private Sub Class_Initialize()
    CurrentDataOffset = 1
    HeaderSeqID = 1
End Sub
